export const shopCategories = [
  { value: "electronics", label: "Electronics" },
  { value: "mobiles", label: "Mobiles & Accessories" },
  { value: "laptops", label: "Laptops & Computers" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "mens_clothing", label: "Men’s Clothing" },
  { value: "womens_clothing", label: "Women’s Clothing" },
  { value: "kids_clothing", label: "Kids’ Clothing" },
  { value: "footwear", label: "Footwear" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "health", label: "Health & Wellness" },
  { value: "groceries", label: "Groceries & Essentials" },
  { value: "home", label: "Home & Kitchen" },
  { value: "furniture", label: "Furniture" },
  { value: "appliances", label: "Home Appliances" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "books", label: "Books & Stationery" },
  { value: "toys", label: "Toys & Games" },
  { value: "automotive", label: "Automotive Accessories" },
  { value: "jewellery", label: "Jewellery" },
  { value: "watches", label: "Watches & Wearables" },
  { value: "gaming", label: "Gaming & Consoles" },
  { value: "music", label: "Musical Instruments" },
  { value: "pet_supplies", label: "Pet Supplies" },
  { value: "office", label: "Office Supplies" },
  { value: "gardening", label: "Gardening & Outdoor" }
];
